CREATE TABLE Clients (
ClientId int PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Phone CHAR(12) NOT NULL
)

CREATE TABLE Mechanics (
MechanicId INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Address VARCHAR(255) NOT NULL
)

CREATE TABLE Models (
ModelId INT PRIMARY KEY IDENTITY NOT NULL,
Name VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Jobs (
JobId INT PRIMARY KEY IDENTITY NOT NULL,
ModelId INT NOT NULL FOREIGN KEY REFERENCES Models(ModelId),
[Status] VARCHAR(11) NOT NULL CHECK ([Status] IN ('Pending', 'In Progress', 'Finished' )) DEFAULT 'Pending',
ClientId INT NOT NULL FOREIGN KEY REFERENCES Clients(ClientId),
MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
IssueDate DATE NOT NULL,
FinishDate DATE
)

CREATE TABLE Orders (
OrderId INT PRIMARY KEY IDENTITY NOT NULL,
JobId INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobId),
IssueDate DATE,
Delivered BIT NOT NULL DEFAULT 0
)

CREATE TABLE Vendors (
VendorId INT PRIMARY KEY IDENTITY NOT NULL,
Name VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Parts (
PartId INT PRIMARY KEY IDENTITY NOT NULL,
SerialNumber VARCHAR(50) NOT NULL UNIQUE,
Description VARCHAR(255),
Price DECIMAL (6, 2) NOT NULL CHECK(Price > 0),
VendorId INT NOT NULL FOREIGN KEY REFERENCES Vendors(VendorId),
StockQty INT NOT NULL CHECK(StockQty >= 0) DEFAULT 0
)

CREATE TABLE OrderParts (
OrderId INT NOT NULL,
PartId INT NOT NULL,
CONSTRAINT Order_Part
PRIMARY KEY(OrderId, PartId),
CONSTRAINT FK_OrderParts_Orders
FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
CONSTRAINT FK_OrderParts_Parts
FOREIGN KEY (PartId) REFERENCES Parts(PartId),
Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1
)

CREATE TABLE PartsNeeded (
JobId INT NOT NULL,
PartId INT NOT NULL,
CONSTRAINT Job_Part
PRIMARY KEY(JobId, PartId),
CONSTRAINT FK_PartsNeeded_Jobs
FOREIGN KEY (JobId) REFERENCES Jobs(JobId),
CONSTRAINT FK_PartsNeeded_Parts
FOREIGN KEY (PartId) REFERENCES Parts(PartId),
Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1
)